
email:
  login: aaa@aaa.com
  password: aaa123456
  provider: Gmail
  to: bbb@aaa.com

server:
  port: 3000

deploys:
  webhook-me:
    url: 'https://github.com/somadl/webhook-me'
    name: Webhook Me
    type: github
    path: ./
    branch: master
    commands:
      - echo 'FOI'
